### ISSUE TITLE
Inconsistent use of measurement units

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#146]
On the Kiwix silo, Configuration 115 is listed as 16.14 Gib, 
![Capture d’écran 2020-02-19 à 18 21 38](https://user-images.githubusercontent.com/21675885/74857985-d84c9300-5344-11ea-8cdc-d849f49d8dfe.png)
yet in the configuration interface the very same is shown to be 17.33 Gb:
![Capture d’écran 2020-02-19 à 18 21 06](https://user-images.githubusercontent.com/21675885/74857988-d8e52980-5344-11ea-8185-2de108f8c095.png)

Looks like there is a problem with size calculation.
Note: I reused and modified an old config, but simply removed/added new contents. I get the same issue creating an empty config, but the size difference is different (8.77 Gb vs. 9.42 Gb)

**Comment by rgaudin** [comment]
Yes, this is simply a conversion issue: `16.14GiB == 17.33GB`.

We've agreed to use `GB` for Card/Config on the Cardshop as this is what the Card manufacturer uses.

**Comment by Popolechien** [comment]
Ah yes. Then we probably need to be consistent with our units.

**Comment by kelson42** [comment]
@rgaudin @Popolechien Duplicate of #389?

**Comment by Popolechien** [comment]
Yup
