### ISSUE TITLE
On last config tab, replace Save with "Order card!"

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#15]
Since this is the last step, Save is an option, but not the most likely one: users will probably want to close the deal and finalize their order. There should therefore be at least a "Next" button but most likely something more of a call to action, like "Order card!/"Place order"/"Confirm delivery address"

Also the Save/Next button(s) should be located under the Selected package list: if I'm looking at Afar then it's fine and not too far, but in English I'd have to scroll quite a bit before finding it.
![capture d ecran 2018-10-17 a 11 03 04](https://user-images.githubusercontent.com/21675885/47075196-530b1880-d1fc-11e8-8783-a91d38051c0f.png)

**Comment by rgaudin** [comment]
See #1.

**Comment by kelson42** [comment]
@rgaudin @Popolechien Not a duplicate of #386?

**Comment by Popolechien** [comment]
Close enough.
