### ISSUE TITLE
possible race condition in worker's await_sdcard

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#161]
Task [L261R5ED0](https://cardshop.hotspot.kiwix.org/orders/L261R5ED0) failed on `failed_to_insert` due to an unexpected result for `get_task(self.task["_id"])` call in `await_sdcard`.

The writing task apparently was a string instead of a dict which may indicate this was called a bit too early (before task was actually created).

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
