### ISSUE TITLE
Increase maximum image size to 512 Gb

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#176]
The current maximum size that can be generated on the Cardshop is 256 Gb, but we've had instances of people maxing this out and, with the increase in the amount of videos we offer, this size does not seem this much far fetched anymore (and someone trying to generate a StackExchange + enwp image would also be very close to the maximum size allowed already. 

400Gb and 512Gb cards are now commercially available, it therefore only makes sense for us to follow the market and be able to provide images within this size range.

**Comment by kelson42** [comment]
Cardshop issue, migrating and reopening.

**Comment by rgaudin** [comment]
The way the hotspot works at the moment is that it:

- creates an image file the required size (not the requested one, but one that can fit all content)
- downloads all content
- copies downloaded file into the image

This means that to create a full 256GB image, you need about 512GB of free space on the disk (twice the content size).

Adding 400GB or 512GB (issue is not clear about what exact sizes to add) to the cardshop would mean that such task would require 800GB+ or 1TB+ of free storage on the worker to run (kiwix-hotspot fails early if there's not enough space though).

Our single worker disk is not large enough to handle any of those two sizes at the moment. This is a worker-sizing issue, not a cardshop issue though so let me know if we should add those sizes (indicating exactly those wanted) ; knowing task would fail on our current worker.

**Comment by kelson42** [comment]
We need to upgrade the worker.

@Popolechien How urgent is the need?

**Comment by Popolechien** [comment]
Mildly - experience has shown that people are willing to pack content to the limit of cards commercially available.
We've had requests already and considering how card prices are dropping I would expect 512Gb to be the new 256Gb in a year or so from now (much like 256 is beginning to be the new 128).

**Comment by rgaudin** [comment]
Obsolete
