### ISSUE TITLE
Cardshop admin should only be notified of failed creations

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#227]
With the increase in cardshop usage I'm also getting an increased number of notifications for orders launched and completed - not much actionable. It would be much better if I would only get `order has failed` notifications that I can react to.

**Comment by kelson42** [comment]
This should probably be handled via a proper filter in email client.

**Comment by kelson42** [comment]
@Popolechien Any update? I‘m not the admin but I believe this is a better approach to do it that way. The proper solution being to make this configurable for each admin via UI.

**Comment by rgaudin** [comment]
Ticket is misleading in that it was Silo Admin receiving for all the silo but this has been changed long time ago. Now we only receive error ones
