### ISSUE TITLE
Cardshop is mixing up writer slots.

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#228]
I launched order [600acd3998c8bfe42651144c](https://cardshop.hotspot.kiwix.org/orders/f/600acd3998c8bfe42651144c), which went fine, but then when the write was done I got two emails: one saying I could remove it from Slot A, and another one to remove it from Slot B (card was in A, as per insert instructions)
![Capture d’écran 2021-01-27 à 12 03 51](https://user-images.githubusercontent.com/21675885/105982571-be104e80-6097-11eb-9282-03897fb95464.png)
![Capture d’écran 2021-01-27 à 12 03 42](https://user-images.githubusercontent.com/21675885/105982573-bf417b80-6097-11eb-8d52-4a19fa49bd37.png)

**Comment by rgaudin** [comment]
OK, might be related to #169. Should not happen.

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
