### ISSUE TITLE
Incorrect fail notification before wiping SD card on writer

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#233]
Here is the scenario from https://cardshop.hotspot.kiwix.org/orders/L439R6035

- Order runs and I get a prompt to insert an SD card
- Insert brand new 200Gb SD card;
- Writer detects it is too small (120 Gb instead of 150 needed)
- Writer sends `fail to insert` email notification
- Writer starts wiping/reformatting process
- Writer sends successful email, writing proceeds.

Basically the first fail message is either unneeded or entirely misleading. Had I been next to the physical writer I would have removed the card with the understanding that it is corrupted, which it was not.

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
