### ISSUE TITLE
Cardshop uploads to warehouse but fails to download to writer

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#235]
The issue is recurring but I can't see any corresponding ticket (maybe #139 or #159 ?).

Issue: ran job [L453R6058](https://cardshop.hotspot.kiwix.org/orders/L453R6058), which for some reason failed (card size too small, which is odd but ok), then relaunched same order for a physical SD card. The 16 Gb image was created and uploaded to the warehouse but more than 24hrs later still hasn't been downloaded to the writer (see [https://cardshop.hotspot.kiwix.org/all-orders/6059bec198c8bf0023678677](https://cardshop.hotspot.kiwix.org/all-orders/6059bec198c8bf0023678677)) .

**Comment by rgaudin** [comment]
It's #86 but let's keep this open as this is clearer about the consequence

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
