### ISSUE TITLE
Uncouple the upload from the image creation process

### ISSUE THREAD

**Issue by kelson42** [offspot/cardshop#253]
This would allow a better fine graded mgmt of the resources (like on the zimfarm).

**Comment by kelson42** [comment]
One problem to care of is the storage, image takes storage space even during the upload.

**Comment by kelson42** [comment]
@rgaudin It seems that the current solution if finally good enough? I would close this ticket as `WONTFIX`.

**Comment by rgaudin** [comment]
Sure. Ticket was relatively thin so I don't recall exactly what was implied.
