### ISSUE TITLE
Writer should allow re-try / re-insert if failing to detect card

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#265]
The physical writer has two slots and isn't very consistent with which letter is assigned to it (see #169 and #228) . 
If writing fails because no card is detected, then one needs to re-launch the full creation process. It would be much simpler to have a re-try button somewhere.

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
