### ISSUE TITLE
Add link to user manual in welcome email

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#269]
Here it is https://docs.google.com/presentation/d/1ZHR54bYGgePKKB9QIFUE9nxy1HgZ_dH9VxkaxcI08PM/edit?usp=sharing

**Comment by rgaudin** [comment]
Looks really nice. Shouldn't we host it as a PDF (for email link) and the source on the repo?

**Comment by Popolechien** [comment]
Happy to create a PDF ([here](https://drive.google.com/file/d/1vgOqmibn1EbuABslvezTrIeOQweWAhx3/view?usp=sharing))
Not sure how we can store the source on the repo since it is a google document. Export it as a .pptx?

**Comment by rgaudin** [comment]
@kelson42 what do you think? I'm afraid if it's not in the repo, we might have difficulties finding it in the distant future.

**Comment by kelson42** [comment]
@rgaudin OK to put it in the repo
