### ISSUE TITLE
502 Bad Gateway Error

### ISSUE THREAD

**Issue by darksixty** [offspot/cardshop#279]
Hello! 

I wasn't sure if y'all were aware or not but when you click on the "Orders" tab and then the blue "Place An Order" button, it presents a 502 bad gateway error. 

I've tried on multiple devices with vpn on or off, lan or wireless, different networks etc. 

Thank you for your time :D

**Comment by rgaudin** [comment]
Hi @darksixty, thank you for the report. I am not affected but I believe it was due to a lack of resource o the Database server. I've changed and restarted that. Could you please check again and come back?

If it's still not working, please share you Cardshop username.

**Comment by darksixty** [comment]
Sure! My username for the card shop is collin.chidiac747@gmail.com

Would having an older account cause this to happen?

**Comment by rgaudin** [comment]
Thanks! It's actually a known but rare issue. Your logo is way too big (8MB!) which is not expected and breaks some assumption. I had to manually remove your logo from your order… The linked ticket is actually #225 so I will close this one.

Your large image is still in your configuration(s). Please change it for a reasonable size (<=1MB?) one in the configuration before creating another order from it.
