### ISSUE TITLE
Unable to browse list of configurations

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#281]
If I am in a Silo with many users (e.g. Orange) that have created many configurations, the user can select to see them all (as opposite to the default `Updated by me`) and then at the bottom of the page click on the link to flip through pages
![Capture d’écran 2021-11-23 à 10 11 28](https://user-images.githubusercontent.com/21675885/142997405-203bd33f-4c23-4a7f-8328-5ee82c195334.png)
However clicking on next will reset the default view to `Updated by me` (the URL correctly indicates `../configurations/?all=oui&page=2`) and clicking on `all` will only show me page one of the config list.

**Comment by rgaudin** [comment]
Ah! Looks like a bug introduced by the translation. Should be `all=yes` and not `oui`
