### ISSUE TITLE
Worker fails at order start

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#284]
[L770R61C8](https://cardshop.hotspot.kiwix.org/orders/L770R61C8)
[L771R61C8](https://cardshop.hotspot.kiwix.org/orders/L771R61C8)
[L769R61C7](https://cardshop.hotspot.kiwix.org/orders/L769R61C7)
[L772R61C8](https://cardshop.hotspot.kiwix.org/orders/L772R61C8)
[L773R61C8](https://cardshop.hotspot.kiwix.org/orders/L773R61C8)

 all returned `Command '['/usr/bin/kiwix-hotspot', 'cache', '--build', '/data', 'reset', '--keep-master']' returned non-zero exit status 1` 
The installer did not even get to start.

**Comment by rgaudin** [comment]
Relaunched what I believe were the two original orders (others being duplicates?): Wikipedia and Gutenberg. It's in progress but first one started creation past this initial cache-reset step.
