### ISSUE TITLE
Library not updating

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#285]
https://library.kiwix.org/zimgit-post-disaster_en_2021-12 was created a few days ago and can be seen in the library, however it is not available in the cardshop.

**Comment by rgaudin** [comment]
Thanks for the report ; the update mechanism was being killed immediately when ran. Seems like resources were OK to display UI but this was not. Makes me wonder if our similar mongodb issue is related to mongo or if it's sloppy-related (maybe both!)

Anyway, it's restarted and Zimgit is present now
