### ISSUE TITLE
Replace Khan academy options with ZIM packages

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#308]
- [x] Remove ability to add Khan (EN/FR/ES) as content (UI)
- [x] Add corresponding ZIM package to all `Configuration` using khan (depends on https://github.com/openzim/zim-requests/issues/327)
- [x] Remove khan from all `Configuration` in manager
- [x] Remove kalite fields from DB

**Comment by rgaudin** [comment]
@Popolechien as of now, KA-Lite has been removed from the Cardshop. It means that:

- it's not possible to add it to any Configuration
- All configurations using it have been updated to include the matching khanacademy ZIM
- Many configuration sizes might now be a lot larger than they previously were and might not fit on the media those were initially thinking about.

**Comment by kelson42** [comment]
@rgaudin I guess new sizes will have to be computed forceach configuration... and DB updated.

**Comment by rgaudin** [comment]
Config sizes have been computed automatically (on save) but that's just a record of the last computed content size. Config size is computed at various times as actual ZIMs matching config changes over time.

The media is not tied to the config and is choosen at order time. For those exceeding 256GB, there is no matching media and those config can't be ordered.
