### ISSUE TITLE
image.yaml builder

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#312]
An `image.yaml` builder needs to be included in Cardshop. Rendered YAML would be included in `Configuration.to_dict()` so it's passed to the scheduler and eventually the worker.

- [ ] references the base-image and its sizes (#310)
- [ ] for non-ZIM content: append OCI image(s) and content file(s)
- [ ] for ZIM content: append file entry using URL
- [x] [kiwix-setup]: reverse proxy cionfig
- [ ] [kiwix-setup]: home generation (needs ZIM icon and metadata)
- [ ] [kiwix-setup]: include `files` image if we have ZIMs (for download feature)
- [ ] add offspot config

**Comment by kelson42** [comment]
I wonder if this would not be better to create a dedicated library now considering that this is foreseen to be integrated in many softwares?

**Comment by rgaudin** [comment]
what other software ? until we have a content catalog, this is gonna be glue taking content name and inserting various values inside a dict that renders as yaml.

If you're thinking about bsf, I don't see how it can be reused at the moment.

But you wrote "many" so maybe we're not on the same page

**Comment by kelson42** [comment]
Kiwix imager will need it

**Comment by rgaudin** [comment]
Oh right, sorry. Will be its own module until then.

No need to bring additional library constraints for now. We'll extract it when we need it.
