### ISSUE TITLE
Update ZIM catalog

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#315]
## Current ZIM catalog is implemented as follows

- http://mirror.download.kiwix.org/library/ideascube.yml is the source data
- it is read/parsed and cached for 1h
- a list of all package IDs can be returned to check whether an ID is (still) in the catalog
- a list of package can be returned by lang (used to select content in UI)
- a list of langs can be returned to build the language filter in UI
- packages are stored as a list of IDs

IDs are the ones from the ideascube YAML. ex `3dprinting.stackexchange.com_en_all.en`. those are computed using the filename (found in [library.xml](http://download.kiwix.org/library/library_zim.xml) `url`) with some replacement and period removal, concatenated with the language code. 

## Proposal

- Current catalog doesn't include favicon data that we need for homepage
- We want to stop maintaining (and thus using first) the parallel ideascube catalog

Switching entirely to OPDS is the goal but the UI work it requires is too much at this stage and not worth the added value ; especially given we have heavy UI works planned for later.

This intermediate step would reproduce the current in-cardshop catalog api by consuming the full list of OPDS entries and caching it.
Main change would be the switch from the ideascube IDs to a new cardshop-specific ID composed of `Name` and `Flavour`.

Additional change would be to fetch the favicon from OPDS-returned URL once needed. Caching TBD.

Hopefully most existing IDs would convert fine in a script ; we can add tweaks for those that don't.

**Comment by kelson42** [comment]
I would recommend to add the `Publisher` information to the IDs from the OPDS to ensure there is no conflict once we will use ZIM created by third parties.
