### ISSUE TITLE
Ressources missing from library

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#316]
I'm currently trying to build a configuration on the cardshop and can't find `Mes p'tits pourquoi`, `Mes p'tites questions`, or `J'aime lire` though they do show on library.kiwix.org

**Comment by rgaudin** [comment]
Use ^F once you've selected French to find them…

<img width="597" alt="Screenshot 2023-01-27 at 14 38 38" src="https://user-images.githubusercontent.com/57929/215112865-59c61d05-6049-48fb-956c-52da2752ffc0.png">
<img width="591" alt="Screenshot 2023-01-27 at 14 38 24" src="https://user-images.githubusercontent.com/57929/215112874-85c6afdf-318c-4384-a27a-d19acabd8c29.png">

**Comment by Popolechien** [comment]
Ok I think I understood: was trying to refresh an old config and had consistently erratic behaviour (files missing, mass deletion of selected content). 
Probably not worth opening a ticket for but I'm flagging this for the record.
