### ISSUE TITLE
Not persisting uploaded files

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#323]
While working on a different ticket, I found out an important bug. Not a cardshop bug per se, but a deployment one.

We were not mounting any persistent storage for the Cardshop manager. Problem is, file uploads (logo/favicon/css) are uploaded to the manager's disk (we have a ticket to save those to the DB).
Whenever the manager container is restarted, all the uploaded files are permanently lost.

I believe we haven't been informed of this because we rarely restart the container and all Orders would follow the Configuration and thus the uploaded files would still be on disk.

`191` Configurations (some are ours) includes at least one file (almost exclusively just the logo).

Symptom of an affected Configuration is a filename and a broken icon in the _Branding_ tab.

<img width="944" alt="Screenshot 2023-05-16 at 10 27 34" src="https://github.com/offspot/cardshop/assets/57929/f51aa38d-fd8b-44e9-ac1b-ff1b2ef9c221">

When working, the logo is displayed.

@Popolechien please keep this in mind should you receive customer complaints. It's been fixed yesterday (2023-05-15).

**Comment by kelson42** [comment]
@rgaudin wow, this was a hairy one!
