### ISSUE TITLE
Remove Custom CSS

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#344]
Custom CSS has never been used and is not supported anymore.

**Comment by kelson42** [comment]
Not convinced - at all - this is a good idea...

**Comment by rgaudin** [comment]
It's a multi-layer issue:

- The UI to input the _custom styles_. The cardshop.
- The creation tool: kiwix-hotspot, image-creator
- The apps on the hotspot that would make use of it.

Offspot apps currently don't support it. Captive portal and hwclock never did. The homepage used to but the DOM has changed (it was ideascube's) and is about to change ~soon.

The creation tool doesn't support it but it may not require any change once the branding is mounted on all apps.

The cardshop must collect the styles and we've seen that just asking for a CSS file is not convenient. Requesting a CSS file has multiple disadvantages:

- it requires technical skills to create. Skills that our users don't have.
- it requires knowing the DOM of the target page 
- it requires designing the target pages for customization or limit it to a single target page using it
- it turns the target page DOM into an API that we can't change without breaking the user's style

For those reasons, we're dropping the custom CSS feature and will later introduce #348

**Comment by rgaudin** [comment]
Fixed in d827cbb
