### ISSUE TITLE
Add "Close" button at end of notification bar, or set a timeout for it to fade away

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#352]
When I update a config I get a confirmation bar on top
![image](https://github.com/offspot/cardshop/assets/21675885/759c044b-4aa9-4d99-ae70-2ceec1e8e389)

However there is no way to remove it, and if I do several updates I am not sure anymore they've been taken into account.

**Comment by rgaudin** [comment]
Fixed in e07c7f2
