### ISSUE TITLE
Replace edupi with file-manager

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#354]
This is mostly cardshop but also `offspot-config` and `metrics`

**Comment by kelson42** [comment]
Indeed 
![image](https://github.com/offspot/cardshop/assets/1029718/e969f754-93d7-48fa-ad75-d77457d7e98e)

Not sure what would be a proper naming though

**Comment by rgaudin** [comment]
The app is now call `File Resources` for now

**Comment by rgaudin** [comment]
Done
