### ISSUE TITLE
`Config Name` is used as hostname instead of `Hotspot Name`

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#355]
When I tried to create an image on imager.kiwix.org, the `Config Name` has been setup to be used as hostname instead of the `Hotspot Name`.

It finishes in `/data/image.yaml` as:
- `offspot.hostname`
- `offspot.ap.domain`
- `offspot.ap.ssid`

See https://imager.kiwix.org/configurations/1006

This leads to:
- issue if `Config Name` is not compliant with SSID/hostname limitations
- Docker containers are not starting at all

**Comment by rgaudin** [comment]
Reported by @benoit74

**Comment by benoit74** [comment]
Looks like the fact that Docker containers are not starting at all is linked to the fact that the hostname `metrics_1` is longer than 8 chars. I changed it to `metrics2` and some containers are starting.

**Comment by rgaudin** [comment]
Wow thanks ; I always use the same for both apparently 😅

**Comment by rgaudin** [comment]
Fixed in 76a69be
