### ISSUE TITLE
List Configs in Order Form sorted by last-edition date

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#360]
I created a configuration and when I go to `Place an Order` the default config is not the last one I edited

![Capture d’écran 2024-01-31 à 14 58 14](https://github.com/offspot/cardshop/assets/21675885/d958b44e-79c3-40ae-bf3a-3da8f3d56235)

**Comment by rgaudin** [comment]
How's this a bug? We never defined it should be the last edited config. It's sorted by creation date, latest first.

**Comment by rgaudin** [comment]
Fixed in e710ed9
