### ISSUE TITLE
Apps and file resources should not be in different tabs

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#364]
I would argue that packages listed under the `File resources` actually are apps, and from a user standpoint it does not make any difference.

![Capture d’écran 2024-02-01 à 13 52 53](https://github.com/offspot/cardshop/assets/21675885/f7b27802-7ff3-410a-affe-c146f9684f25)

**Comment by Popolechien** [comment]
On a side note there is a "File resources" in the apps tab, that's quite confusing.

**Comment by rgaudin** [comment]
What user are you talking about? The one making the card or the one using the hotspot?

For the latter, it's presented the same way and they'll have to find out by testing it.
For the cardshop user, who is supposedly browsing through the catalog to find appropriate tools and content, it's important to easily understand whether he's adding an app (usable online by end-users) or some resources that must be downloaded and have additional requirements (be it android, windows or else).

Mixing both doesn't make more sense than separating ZIMs from them. That's where I started and I can tell you it's a big mess.

**Comment by rgaudin** [comment]
I understand wording is not well chosen. But we can change that easily

**Comment by Popolechien** [comment]
I would argue that `Apps` are pretty universally recognized as "things to be downloaded on a phone". 

Wikifundi can not, and I would put that card along with the zim files in "Content".

Overall we can put two sets of things on the hotspot:
1. Things that can be downloaded (e.g. Apps)
2. Things that will be browsed from the hotspot itself (Wikifundi, zim files)

**Comment by rgaudin** [comment]
We've agreed on not doing this at the moment.
