### ISSUE TITLE
Display of available zim files and apps should default to the language selected on the first tab

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#366]
Most users are English-speaking and going through the selector and its 200+ languages is tedious: we could ease the selection process by having the available zim files listed in that language already

![Capture d’écran 2024-02-01 à 13 56 55](https://github.com/offspot/cardshop/assets/21675885/bb3d1fbd-9f46-4f07-bdfc-abcb974f16a7)

![Capture d’écran 2024-02-01 à 13 56 49](https://github.com/offspot/cardshop/assets/21675885/a336eb47-1f2e-44ab-83b0-bb5f88d4fa4f)

**Comment by rgaudin** [comment]
Good point

**Comment by rgaudin** [comment]
Fixed in d01e346
