### ISSUE TITLE
Remove "Static Content Packages" header

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#367]
The meaning is obscure and has no bearing on user behaviour / choices.

Same thing for `Available ZIMs` - most hotspot users don't know nor care what a zim file is. Only leave the language selector on top of the left column, and change right column header to "selected"

![Capture d’écran 2024-02-01 à 13 56 49](https://github.com/offspot/cardshop/assets/21675885/a8151a34-51c9-41e9-a0a2-c55136616e84)

**Comment by rgaudin** [comment]
(!) I remember removing it 😅

**Comment by rgaudin** [comment]
Fixed in ab90333
