### ISSUE TITLE
Rename ZIMs tab

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#369]
Hotspot users are not really interested in the subtleties of file formats, I would suggest renaming the ZIMs tab to something more in line with `General`, `Branding` and `Apps`, e.g. _`Content`_

**Comment by rgaudin** [comment]
Is `Content` an example or the desired value?

**Comment by Popolechien** [comment]
Desired value as it tells it like it is.

**Comment by rgaudin** [comment]
Fixed in ccc5f21
