### ISSUE TITLE
Move File manager to File resources tab

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#372]
The file manager is a very specific tool and use case that would probably benefit from being set aside from the rest.

In the spirit of #364 I suggest moving the File manager to the File resources tab (along with the `Preloaded File Resources` text box)
- `Preloaded file resources` should be renamed to "Import external files"
- Descriptor should be clearer _"Uncompressed ZIP folder archive of files to initialize with"_ is very obscure. I suggest _`indicate the URL of a ZIP archive to fetch and pre-install on the file manager`_
- The whole tab should be renamed to "External files"

**Comment by rgaudin** [comment]
Fixed in 0cd229e
