### ISSUE TITLE
Place an Order page should become Confirm order

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#378]
Currently the page offers a lot of choices that are or have been deprecated. This should be turned into a much simplified Confirm order page, with the default configuration being the last open config (if people have several config they either have downloaded them already and don't need to regenerate them, or if they're older than 14 days then probably will want to check them out one last time before ordering. 

![image](https://github.com/offspot/cardshop/assets/21675885/2c935fd4-87c8-463f-bea5-c38b6ef39415)

**Comment by rgaudin** [comment]
Fixed in cedc8f9
