### ISSUE TITLE
Trailsense package returns 400 Bad Request

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#380]
It's trying to ping com.kylecorry.trail_sense.kiwix.hotspot but to no avail and I can't download the package.

**Comment by rgaudin** [comment]
Can you share a screenshot?

**Comment by Popolechien** [comment]
Here you go
![Screenshot (2 févr  2024 16_27_55)](https://github.com/offspot/cardshop/assets/21675885/9e70f2b7-8b1e-4b15-8af5-ae922e6727b8)

**Comment by rgaudin** [comment]
Thank you ; I can repro. Weird it only affects those two packages. Looks like a reverse issue ; content is fine from files endpoint.

**Comment by rgaudin** [comment]
Fixed in https://github.com/offspot/container-images/commit/684de3bfc7168d129577ef6bb1c4825daafc3835
