### ISSUE TITLE
Replace "Place order" button with "Save and launch imager"

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#384]
The CTA is clearer I believe.

**Comment by Popolechien** [comment]
Also replace the cart icon with a rocket? 
<img src="https://github.com/offspot/cardshop/assets/21675885/bb79ffa8-6c57-46f2-828d-8fb73ec9b049" width="50">

https://www.flaticon.com/free-icon/rocket_1323780

**Comment by rgaudin** [comment]
I specifically asked you whether you wanted this button to save before placing an order and you said so. 😵‍💫

**Comment by Popolechien** [comment]
Ok my bad because it's always been clear to me that it should. Miscommunication it was.

**Comment by rgaudin** [comment]
Fixed in c2dfba5 ; named button “Save & Request” as “Save and launch imager” seems very confusing. Propose a better wording if you have one
