### ISSUE TITLE
Units are not consistent

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#389]
Image size is in GB but available space is in GiB

![Capture d’écran 2024-02-07 à 12 42 48](https://github.com/offspot/cardshop/assets/21675885/94988be8-e08e-4b0d-b418-59e92280bd53)

**Comment by rgaudin** [comment]
Fixed in d24df90 ; harmonized to use binary (GiB) notation everywhere but for SD card Size which are advertised/sold as decimal.
