### ISSUE TITLE
Update to landing page

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#390]
Currently the welcome message reads thus:

```
Welcome [username]!

This is an online shop where you can prepare, order and download custom images to run on your RaspberryPi.

Placing such an order requires the following from you:

A [configuration](https://imager.kiwix.org/configurations/): this is where you select the content that will be available on your hotspot, as well as a few options options (WiFi name, logo, etc.);
A [recipient address](https://imager.kiwix.org/addresses/) to send the download link to. This can be you, or anyone else;
An [Order](https://imager.kiwix.org/orders/) to confirm the configuration you want, and to which address you want it sent to.

If you require assistance, please contact [hotspot@kiwix.org](mailto:hotspot@kiwix.org).

If you are through with the Imager, you also have the ability to [delete your account](https://imager.kiwix.org/delete).

```

I suggest removing the grey/green box around the text, and because of recent changes and also the fact that individual, paid users do not register an actual name but are only identified via their email address, I suggest the following:

----

Welcome!

This is an online shop where you can prepare custom images to run on your RaspberryPi as a local wifi hotspot.

The **[Configuration](https://imager.kiwix.org/configurations/)** tab at the top lets you select the content that will be available on your hotspot, as well as a decide on a few features (WiFi name, language, etc.).

Image creation may take from a few minutes to a few hours. Once the image is ready, a download link will be sent to [user address].

If you run into problems, please contact [hotspot@kiwix.org](mailto:hotspot@kiwix.org).

If you are through with the Imager, you also have the ability to [delete your account](https://imager.kiwix.org/delete).

**Comment by rgaudin** [comment]
Fixed in 08d049f
