### ISSUE TITLE
Concurency issue on writer task

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#62]
For some reason, two writer-workers on the same host could pick-up the same task. This should not happen.

```
INFO:base:Starting to work on 5c6a893698c8bf323d6a1d1d
INFO:base:updating task #5c6a893698c8bf323d6a1d1d status to: waiting_for_card
INFO:base:Starting await_sdcard on slot A
INFO:base:Waiting for the SD-card to be inserted...
```

```
INFO:base:requesting task #5c6a893698c8bf323d6a1d1d to scheduler.
INFO:base:Starting to work on 5c6a893698c8bf323d6a1d1d
INFO:base:updating task #5c6a893698c8bf323d6a1d1d status to: waiting_for_card
INFO:base:Starting await_sdcard on slot B
INFO:base:Waiting for the SD-card to be inserted...
```

**Comment by kelson42** [comment]
@rgaudin Hmmm, looks like a typical scenario for a race condition.

**Comment by kelson42** [comment]
I hope this is not valid anymore, looks like current Kiwix writer is configured to deal with 2-3 cards at the same time.

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
