### ISSUE TITLE
Writer not generating required number of cards

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#65]
Ordered two (2) cards via cardshop: when the file was generated, I received an email requesting a card be inserted in slot B. When writing was completed, I received a message requesting I ship both cards:
- Writer did not make use of slot A;
- Writer did not count the number of cards actually generated/written.

**Comment by kelson42** [comment]
@Popolechien Still a valid bug?

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
