### ISSUE TITLE
Contradictory messages upon completion

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#70]
Upon writing card I get both a "failed" and "completed" email. FWIW the card worked in the end so the issue is with the incorrect fail notification. I did not check if the account was refunded of credits.

![Capture d’écran 2019-03-27 à 10 01 37](https://user-images.githubusercontent.com/21675885/55063486-5c849080-5078-11e9-8bf4-f2ce7521fc28.png)

**Comment by rgaudin** [comment]
Thanks, this is an interesting issue.
As you can see at https://cardshop.hotspot.kiwix.org/all-orders/5c9a211e98c8bf00217463f9

![Screen Shot 2019-03-27 at 9 32 45 AM](https://user-images.githubusercontent.com/57929/55065264-66f05b80-5073-11e9-89b6-fd7006fa4649.png)

What happened is that at 7:38, you confirmed insertion without the card inserted (hence the 0bytes capacity) but *for some reason*, it retried a minute later and detected the card.

While it sounds robust, it is not the intended behavior and should have failed completely on 7:38.

Question: did you re-hit the email link a second time after properly inserting the card?

**Comment by Popolechien** [comment]
Nope. But what I did was remove a card that was already in the slot, reinserted it, and _then_ clicked on the email link.

**Comment by rgaudin** [comment]
OK thanks for the feedback.

We might encounter again that browser/email/whatever link discovery/preview issue.
Card inserted link were designed login-less and action-less to ease the operator's flow but should it be problematic we might have to ask the operator to hit a button on that page to confirm the action.

I'll investigate.

**Comment by Popolechien** [comment]
Confirm that the issue reappeared today 
https://cardshop.hotspot.kiwix.org/orders/L58R5CE7
Hit the link only once, both emails arrived almost simultaneously (fail before writing in progress).

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
