### ISSUE TITLE
Enable "retry" upon write fail

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#74]
Currently if card writing fails (for ex. I inserted a 32Gb card instead of 128Gb) we have to restart the whole process of creating and uploading an image. It would be much simpler if the fail notification would allow for the user to retry writing the card.

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
