### ISSUE TITLE
Create interface language setting

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#77]
When creating a new user, allow selection of default interface language (FR/EN at the moment, ultimately more if we can). I suspect a lot of French speaker are not comfortable with English (and vice-versa).

**Comment by rgaudin** [comment]
This would mean internationalizing the cardshop and creating/maintaining translations. Is that what we want?

**Comment by Popolechien** [comment]
If we keep working with the likes of Orange: yes.
