### ISSUE TITLE
`failed_to_insert` did not release `pending_end_of_writes`

### ISSUE THREAD

**Issue by rgaudin** [offspot/cardshop#86]
During Order `5cd99e6498c8bf002373f42e`, worker (`ch-kiwix-writer`) downloaded its image using task `5cd9bd7798c8bf002373f873`.

Download finished properly and task entered `pending_end_of_writes` until the write is complete.

The writing task ended-up on `failed_to_insert` but the `pending_image_removal` was never triggered.

The worker is thus still considered *busy* with that download task.

**Comment by rgaudin** [comment]
Also images are never deleted on the warehouse #110

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
